import type {
  Product,
  Category,
  Supplier,
  Customer,
  Invoice,
  StockMovement,
  AIInsight, 
  Batch,
  AuditLog,
  WarehouseProp,
} from "./types"

export const MOCK_WAREHOUSES: WarehouseProp[] = [
  {
    id: "1",
    name: "Main Warehouse",
    code: "WH-MAIN",
    address: "1234 Industrial Park Dr",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90001",
    country: "USA",
    managerId: "1",
    managerName: "Admin User",
    isActive: true,
    capacity: 10000,
    currentUtilization: 6500,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "East Coast Distribution",
    code: "WH-EAST",
    address: "567 Commerce Blvd",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "USA",
    isActive: true,
    capacity: 8000,
    currentUtilization: 5200,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "3",
    name: "Midwest Hub",
    code: "WH-MIDWEST",
    address: "789 Logistics Way",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "USA",
    isActive: true,
    capacity: 12000,
    currentUtilization: 4800,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
]

export const MOCK_CATEGORIES: Category[] = [
  {
    categoryId: "1",
    name: "Electronics",
    description: "Electronic devices and accessories",
    isActive: true,
   },
  {
    categoryId: "2",
    name: "Clothing",
    description: "Apparel and fashion items",
    isActive: true,
   },
  {
    categoryId: "3",
    name: "Food & Beverage",
    description: "Food and drink products",
    isActive: true,
   },
  {
    categoryId: "4",
    name: "Pharmaceuticals",
    description: "Medical and pharmaceutical products",
    isActive: true,
   },
  {
    categoryId: "5",
    name: "Home & Garden",
    description: "Home improvement and garden supplies",
    isActive: true,
   },
]

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "1",
    name: "Tech Distributors Inc.",
    code: "SUP-TECH-001",
    email: "contact@techdist.com",
    phone: "+1-555-0101",
    address: "123 Tech Street",
    city: "Silicon Valley",
    state: "CA",
    zipCode: "94000",
    country: "USA",
    contactPerson: "John Tech",
    paymentTerms: "Net 30",
    rating: 4.5,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Fashion Wholesale Co.",
    code: "SUP-FASH-001",
    email: "orders@fashionwholesale.com",
    phone: "+1-555-0102",
    address: "456 Fashion Ave",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "USA",
    contactPerson: "Jane Style",
    paymentTerms: "Net 15",
    rating: 4.2,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Fresh Foods Supply",
    code: "SUP-FOOD-001",
    email: "info@freshfoods.com",
    phone: "+1-555-0103",
    address: "789 Market Street",
    city: "Portland",
    state: "OR",
    zipCode: "97201",
    country: "USA",
    contactPerson: "Bob Fresh",
    paymentTerms: "Net 7",
    rating: 4.8,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "MediPharm Suppliers",
    code: "SUP-MED-001",
    email: "orders@medipharm.com",
    phone: "+1-555-0104",
    address: "321 Healthcare Ln",
    city: "Boston",
    state: "MA",
    zipCode: "02101",
    country: "USA",
    contactPerson: "Dr. Sarah Med",
    paymentTerms: "Net 30",
    rating: 4.9,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
]

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "1",
    name: "Acme Corporation",
    code: "CUST-ACME-001",
    email: "purchasing@acme.com",
    phone: "+1-555-1001",
    address: "100 Business Park",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    country: "USA",
    creditLimit: 50000,
    outstandingBalance: 12500,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Global Retail Inc.",
    code: "CUST-GLOB-001",
    email: "orders@globalretail.com",
    phone: "+1-555-1002",
    address: "200 Commerce St",
    city: "Chicago",
    state: "IL",
    zipCode: "60602",
    country: "USA",
    creditLimit: 100000,
    outstandingBalance: 25000,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Metro Stores",
    code: "CUST-METRO-001",
    email: "purchasing@metrostores.com",
    phone: "+1-555-1003",
    address: "300 Retail Row",
    city: "Miami",
    state: "FL",
    zipCode: "33101",
    country: "USA",
    creditLimit: 75000,
    outstandingBalance: 8000,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
]

export const MOCK_BATCHES: Batch[] = [
  {
    id: "1",
    batchNumber: "BATCH-MED-001",
    productId: "7",
    productName: "Pain Relief Tablets",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    quantity: 500,
    manufacturingDate: new Date("2024-01-01"),
    expiryDate: new Date("2025-12-31"),
    supplierBatchNumber: "SUP-MED-2024-001",
    status: "active",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    batchNumber: "BATCH-FOOD-001",
    productId: "5",
    productName: "Premium Coffee Beans",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    quantity: 100,
    manufacturingDate: new Date("2024-02-01"),
    expiryDate: new Date("2024-08-01"),
    supplierBatchNumber: "FRESH-COFFEE-2024-Q1",
    notes: "Arabica beans from Colombia",
    status: "active",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "3",
    batchNumber: "BATCH-MED-002",
    productId: "7",
    productName: "Pain Relief Tablets",
    warehouseId: "2",
    warehouseName: "East Coast Distribution",
    quantity: 300,
    manufacturingDate: new Date("2023-06-01"),
    expiryDate: new Date("2024-05-31"),
    supplierBatchNumber: "SUP-MED-2023-045",
    status: "active",
    notes: "Expiring soon - prioritize for distribution",
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-02-20"),
  },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    sku: "LAPTOP-PRO-001",
    name: "Professional Laptop",
    description: "High-performance laptop for business use with 16GB RAM and 512GB SSD",
    categoryId: "1",
    categoryName: "Electronics",
    price: 1299.99,
    cost: 899.99,
    stock: 45,
    reorderLevel: 10,
    reorderQuantity: 20,
    supplierId: "1",
    supplierName: "Tech Distributors Inc.",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    hasBatchTracking: false,
    hasExpiryTracking: false,
    unit: "unit",
    barcode: "7891234567890",
    isActive: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "2",
    sku: "PHONE-PRO-001",
    name: "Smartphone Pro",
    description: "Latest generation smartphone with 5G connectivity and 256GB storage",
    categoryId: "1",
    categoryName: "Electronics",
    price: 899.99,
    cost: 599.99,
    stock: 8,
    reorderLevel: 15,
    reorderQuantity: 25,
    supplierId: "1",
    supplierName: "Tech Distributors Inc.",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    hasBatchTracking: false,
    hasExpiryTracking: false,
    unit: "unit",
    barcode: "7891234567891",
    isActive: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-22"),
  },
  {
    id: "3",
    sku: "TSHIRT-COT-001",
    name: "Premium Cotton T-Shirt",
    description: "100% organic cotton t-shirt, breathable and comfortable",
    categoryId: "2",
    categoryName: "Clothing",
    price: 29.99,
    cost: 12.99,
    stock: 150,
    reorderLevel: 50,
    reorderQuantity: 100,
    supplierId: "2",
    supplierName: "Fashion Wholesale Co.",
    warehouseId: "2",
    warehouseName: "East Coast Distribution",
    hasBatchTracking: false,
    hasExpiryTracking: false,
    unit: "piece",
    barcode: "7891234567892",
    isActive: true,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "4",
    sku: "JEANS-DEN-001",
    name: "Classic Denim Jeans",
    description: "Durable denim jeans with stretch fabric for comfort",
    categoryId: "2",
    categoryName: "Clothing",
    price: 59.99,
    cost: 29.99,
    stock: 75,
    reorderLevel: 30,
    reorderQuantity: 50,
    supplierId: "2",
    supplierName: "Fashion Wholesale Co.",
    warehouseId: "2",
    warehouseName: "East Coast Distribution",
    hasBatchTracking: false,
    hasExpiryTracking: false,
    unit: "piece",
    barcode: "7891234567893",
    isActive: true,
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "5",
    sku: "COFFEE-PREM-001",
    name: "Premium Coffee Beans",
    description: "100% Arabica coffee beans from Colombia, 1kg package",
    categoryId: "3",
    categoryName: "Food & Beverage",
    price: 24.99,
    cost: 14.99,
    stock: 100,
    reorderLevel: 25,
    reorderQuantity: 50,
    supplierId: "3",
    supplierName: "Fresh Foods Supply",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    hasBatchTracking: true,
    hasExpiryTracking: true,
    unit: "kg",
    barcode: "7891234567894",
    isActive: true,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "6",
    sku: "HEADPHONE-WL-001",
    name: "Wireless Headphones",
    description: "Premium noise-cancelling wireless headphones with 30-hour battery life",
    categoryId: "1",
    categoryName: "Electronics",
    price: 199.99,
    cost: 129.99,
    stock: 62,
    reorderLevel: 20,
    reorderQuantity: 30,
    supplierId: "1",
    supplierName: "Tech Distributors Inc.",
    warehouseId: "3",
    warehouseName: "Midwest Hub",
    hasBatchTracking: false,
    hasExpiryTracking: false,
    unit: "unit",
    barcode: "7891234567895",
    isActive: true,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "7",
    sku: "MED-PAIN-001",
    name: "Pain Relief Tablets",
    description: "Over-the-counter pain relief medication, 500mg, 100 tablets per box",
    categoryId: "4",
    categoryName: "Pharmaceuticals",
    price: 12.99,
    cost: 7.99,
    stock: 800,
    reorderLevel: 200,
    reorderQuantity: 500,
    supplierId: "4",
    supplierName: "MediPharm Suppliers",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    hasBatchTracking: true,
    hasExpiryTracking: true,
    unit: "box",
    barcode: "7891234567896",
    isActive: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-02-25"),
  },
]

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "1",
    invoiceNumber: "PUR-2024-001",
    type: "purchase",
    status: "confirmed",
    supplierId: "1",
    supplierName: "Tech Distributors Inc.",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    subtotal: 13499.85,
    taxAmount: 1349.99,
    discountAmount: 0,
    total: 14849.84,
    paymentMethod: "Bank Transfer",
    paymentStatus: "paid",
    createdBy: "1",
    createdByName: "Admin User",
    items: [
      {
        id: "1",
        invoiceId: "1",
        productId: "1",
        productName: "Professional Laptop",
        quantity: 10,
        unitPrice: 899.99,
        discountPercent: 0,
        taxPercent: 10,
        totalPrice: 8999.9,
      },
      {
        id: "2",
        invoiceId: "1",
        productId: "2",
        productName: "Smartphone Pro",
        quantity: 5,
        unitPrice: 599.99,
        discountPercent: 0,
        taxPercent: 10,
        totalPrice: 2999.95,
      },
    ],
    createdAt: new Date("2024-02-20T10:30:00"),
    confirmedAt: new Date("2024-02-20T11:00:00"),
  },
  {
    id: "2",
    invoiceNumber: "SAL-2024-001",
    type: "sales",
    status: "confirmed",
    customerId: "1",
    customerName: "Acme Corporation",
    warehouseId: "1",
    warehouseName: "Main Warehouse",
    subtotal: 2199.98,
    taxAmount: 219.99,
    discountAmount: 110,
    total: 2309.97,
    paymentMethod: "Credit Card",
    paymentStatus: "paid",
    createdBy: "2",
    createdByName: "Cashier User",
    items: [
      {
        id: "3",
        invoiceId: "2",
        productId: "1",
        productName: "Professional Laptop",
        quantity: 1,
        unitPrice: 1299.99,
        discountPercent: 5,
        taxPercent: 10,
        totalPrice: 1299.99,
      },
      {
        id: "4",
        invoiceId: "2",
        productId: "2",
        productName: "Smartphone Pro",
        quantity: 1,
        unitPrice: 899.99,
        discountPercent: 5,
        taxPercent: 10,
        totalPrice: 899.99,
      },
    ],
    createdAt: new Date("2024-02-21T14:15:00"),
    confirmedAt: new Date("2024-02-21T14:20:00"),
    dueDate: new Date("2024-03-21"),
  },
]

export const MOCK_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: "1",
    productId: "1",
    productName: "Professional Laptop",
    toWarehouseId: "1",
    toWarehouseName: "Main Warehouse",
    quantity: 10,
    type: "IN",
    reason: "purchase",
    referenceId: "1",
    referenceType: "invoice",
    createdBy: "1",
    createdByName: "Admin User",
    approvedBy: "1",
    approvedByName: "Admin User",
    createdAt: new Date("2024-02-20T11:00:00"),
    approvedAt: new Date("2024-02-20T11:00:00"),
  },
  {
    id: "2",
    productId: "2",
    productName: "Smartphone Pro",
    toWarehouseId: "1",
    toWarehouseName: "Main Warehouse",
    quantity: 5,
    type: "IN",
    reason: "purchase",
    referenceId: "1",
    referenceType: "invoice",
    createdBy: "1",
    createdByName: "Admin User",
    approvedBy: "1",
    approvedByName: "Admin User",
    createdAt: new Date("2024-02-20T11:00:00"),
    approvedAt: new Date("2024-02-20T11:00:00"),
  },
  {
    id: "3",
    productId: "1",
    productName: "Professional Laptop",
    fromWarehouseId: "1",
    fromWarehouseName: "Main Warehouse",
    quantity: 1,
    type: "OUT",
    reason: "sales",
    referenceId: "2",
    referenceType: "invoice",
    createdBy: "2",
    createdByName: "Cashier User",
    approvedBy: "2",
    approvedByName: "Cashier User",
    createdAt: new Date("2024-02-21T14:20:00"),
    approvedAt: new Date("2024-02-21T14:20:00"),
  },
]

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: "1",
    type: "critical",
    category: "expiry_alert",
    title: "Batch Expiring Soon",
    description: "Batch BATCH-MED-002 of Pain Relief Tablets will expire in 65 days (May 31, 2024).",
    recommendation:
      "Prioritize distribution of this batch to prevent waste. Consider promotional pricing to move stock.",
    productId: "7",
    productName: "Pain Relief Tablets",
    impact: "high",
    confidence: 1.0,
    isActionable: true,
    createdAt: new Date("2024-03-26T08:00:00"),
  },
  {
    id: "2",
    type: "warning",
    category: "stock_level",
    title: "Stock Below Reorder Level",
    description:
      "Smartphone Pro has 8 units in stock, which is below the reorder level of 15 units. Lead time is 7 days.",
    recommendation: "Initiate reorder of 25 units from Tech Distributors Inc. to prevent stockout.",
    productId: "2",
    productName: "Smartphone Pro",
    impact: "high",
    confidence: 0.95,
    isActionable: true,
    createdAt: new Date("2024-03-26T08:00:00"),
  },
  {
    id: "3",
    type: "info",
    category: "demand_forecast",
    title: "Increased Demand Detected",
    description: "Professional Laptop shows 35% increase in sales over the past 30 days compared to previous period.",
    recommendation: "Consider increasing reorder quantity to 30 units and adjusting reorder level to 15 units.",
    productId: "1",
    productName: "Professional Laptop",
    impact: "medium",
    confidence: 0.85,
    isActionable: true,
    createdAt: new Date("2024-03-26T08:00:00"),
  },
  {
    id: "4",
    type: "success",
    category: "stock_level",
    title: "Optimal Inventory Levels",
    description: "Cotton T-Shirt inventory levels are healthy at 150 units, well above the reorder threshold.",
    productId: "3",
    productName: "Premium Cotton T-Shirt",
    impact: "low",
    confidence: 0.9,
    isActionable: false,
    createdAt: new Date("2024-03-26T08:00:00"),
  },
  {
    id: "5",
    type: "warning",
    category: "anomaly",
    title: "Unusual Stock Movement",
    description:
      "Detected higher than expected stock adjustments for Wireless Headphones in the past week (12 adjustments vs. avg 2).",
    recommendation:
      "Review recent stock adjustments and investigate potential issues with inventory accuracy or theft.",
    productId: "6",
    productName: "Wireless Headphones",
    impact: "high",
    confidence: 0.78,
    isActionable: true,
    createdAt: new Date("2024-03-25T15:30:00"),
  },
  {
    id: "6",
    type: "info",
    category: "supplier_performance",
    title: "Excellent Supplier Performance",
    description: "MediPharm Suppliers maintains 98% on-time delivery rate with 4.9/5.0 rating over the past 6 months.",
    recommendation: "Consider establishing preferred supplier status and negotiating volume discounts.",
    impact: "low",
    confidence: 0.92,
    isActionable: true,
    createdAt: new Date("2024-03-25T10:00:00"),
  },
  {
    id: "7",
    type: "info",
    category: "pricing",
    title: "Price Optimization Opportunity",
    description:
      "Classic Denim Jeans has stable demand and low competition. Analysis suggests 10% price increase would not impact sales volume.",
    recommendation:
      "Consider increasing price from $59.99 to $65.99 to improve profit margin by approximately $6 per unit.",
    productId: "4",
    productName: "Classic Denim Jeans",
    impact: "medium",
    confidence: 0.73,
    isActionable: true,
    createdAt: new Date("2024-03-24T09:00:00"),
  },
]

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "1",
    userId: "1",
    userName: "Admin User",
    userRole: "admin",
    action: "create",
    entityType: "product",
    entityId: "7",
    entityName: "Pain Relief Tablets",
    metadata: { sku: "MED-PAIN-001", category: "Pharmaceuticals" },
    ipAddress: "192.168.1.100",
    createdAt: new Date("2024-01-10T10:30:00"),
  },
  {
    id: "2",
    userId: "1",
    userName: "Admin User",
    userRole: "admin",
    action: "approve",
    entityType: "invoice",
    entityId: "1",
    entityName: "PUR-2024-001",
    changes: {
      status: { old: "draft", new: "confirmed" },
    },
    metadata: { type: "purchase", total: 14849.84 },
    ipAddress: "192.168.1.100",
    createdAt: new Date("2024-02-20T11:00:00"),
  },
  {
    id: "3",
    userId: "2",
    userName: "Cashier User",
    userRole: "cashier",
    action: "create",
    entityType: "invoice",
    entityId: "2",
    entityName: "SAL-2024-001",
    metadata: { type: "sales", customer: "Acme Corporation", total: 2309.97 },
    ipAddress: "192.168.1.105",
    createdAt: new Date("2024-02-21T14:15:00"),
  },
  {
    id: "4",
    userId: "3",
    userName: "Auditor User",
    userRole: "auditor",
    action: "view",
    entityType: "invoice",
    entityId: "2",
    entityName: "SAL-2024-001",
    metadata: { report: "monthly_audit" },
    ipAddress: "192.168.1.110",
    createdAt: new Date("2024-03-01T09:15:00"),
  },
  {
    id: "5",
    userId: "1",
    userName: "Admin User",
    userRole: "admin",
    action: "update",
    entityType: "product",
    entityId: "2",
    entityName: "Smartphone Pro",
    changes: {
      reorderLevel: { old: 8, new: 15 },
      reorderQuantity: { old: 15, new: 25 },
    },
    metadata: { reason: "AI recommendation" },
    ipAddress: "192.168.1.100",
    createdAt: new Date("2024-02-22T16:45:00"),
  },
]
// 
 